### PR TITLE
Car state checks by CANbus

### PR DESCRIPTION
**Pull request by beehphy**
There were some major changes to the project structure when sussing out the USB gremlins. Be sure to follow the setup guide as the ASF version has changed.

### CODE REVIEW

**Comment by rstreif** [comment]
Jesse, is this PR ready to be merged into master? Do you have any more changes pending?

**Comment by beehphy** [comment]
The only other change I would appreciate is updating my email address on the readme.md

**Comment by magnusfeuer** [comment]
@beehphy Feel free to update the email address, or post it here so that I can do it.

**Comment by beehphy** [comment]
Maybe I updated it in the merge you just accepted. Looks correct now. Thx.

**Pull request merged**
