### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by smiller6**
* Add field support manual
* Update readme in preparation for release (0.2) candidacy
* Rename a file to use hyphens instead of spaces

### CODE REVIEW

**Comment by smiller6** [comment]
@rstreif 
I'd very much appreciate any feedback on the documentation, should you desire.

Otherwise I'll just be merging this within the next day.

Thanks

**Comment by rstreif** [comment]
@smiller6 yes, I'll have a look shortly.

**Review by rstreif — APPROVED** [review]
@smiller6 Great job. Some comments:
field-support-manual.md
* Line 130: Typo: Cellular
* Line 193: Typo: inserted
* Line 206++:  "...if the host has not
 +actively communicated with the host for some time.": duplicate "host" should be "V2X board" for the first instance.

**Comment by smiller6** [comment]
Thanks for the feedback, @rstreif . I'll correct those and merge this up.

**Pull request merged**
